# Generated by Django 5.2.1 on 2025-06-24 14:13

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('correct_index', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
            },
        ),
    ]
