# Generated by Django 5.2.2 on 2025-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
