# Generated by Django 5.2.2 on 2025-08-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_alter_roadmap_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmapquestion',
            name='position',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='generated_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
