# Generated by Django 5.2.2 on 2025-08-18 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_remove_roadmapquestion_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roadmap',
            unique_together={('user', 'title')},
        ),
    ]
