# Generated by Django 5.2.2 on 2025-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='embedding_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='taste_keywords_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
