# Generated by Django 5.2.1 on 2025-06-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmapquestion',
            options={'managed': False},
        ),
    ]
