# Generated by Django 5.2.1 on 2025-05-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.SmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuestionAttempts",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("attempt_count", models.IntegerField(blank=True, null=True)),
                ("correct_attempts", models.IntegerField(blank=True, null=True)),
                ("incorrect_attempts", models.IntegerField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_time_spent_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "question_attempts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField()),
            ],
            options={
                "db_table": "question_choice",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuestionQuestion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField()),
            ],
            options={
                "db_table": "question_question",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("topic", models.CharField(blank=True, null=True)),
                ("difficulty", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("options", models.TextField()),
                ("correct_index", models.IntegerField()),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "questions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoadmapQuestion",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "roadmap_id",
                        "question_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "roadmap_question",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roadmaps",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "roadmaps",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("password_hash", models.TextField(blank=True, null=True)),
                (
                    "auth_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "provider_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfiles",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="users.users",
                    ),
                ),
                ("learning_streak", models.IntegerField(blank=True, null=True)),
                ("strong_topics", models.TextField(blank=True, null=True)),
                ("weak_topics", models.TextField(blank=True, null=True)),
                ("average_accuracy", models.FloatField(blank=True, null=True)),
                ("avg_difficulty", models.FloatField(blank=True, null=True)),
                ("average_time_per_question", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_profiles",
                "managed": False,
            },
        ),
    ]
