# Generated by Django 5.2.1 on 2025-05-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.DeleteModel(
            name="QuestionAttempts",
        ),
        migrations.DeleteModel(
            name="QuestionChoice",
        ),
        migrations.DeleteModel(
            name="QuestionQuestion",
        ),
        migrations.DeleteModel(
            name="Questions",
        ),
        migrations.DeleteModel(
            name="RoadmapQuestion",
        ),
        migrations.DeleteModel(
            name="Roadmaps",
        ),
    ]
