# Generated by Django 5.2.2 on 2025-06-08 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('auth_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('learning_streak', models.IntegerField(blank=True, null=True)),
                ('strong_topics', models.JSONField(blank=True, default=list)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('average_accuracy', models.FloatField(blank=True, null=True)),
                ('avg_difficulty', models.FloatField(blank=True, null=True)),
                ('average_time_per_question', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
