# Generated by Django 5.2.1 on 2025-05-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answers",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("selected_index", models.IntegerField()),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("time_taken_seconds", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "answers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuestionAttempts",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("attempt_count", models.IntegerField(blank=True, null=True)),
                ("correct_attempts", models.IntegerField(blank=True, null=True)),
                ("incorrect_attempts", models.IntegerField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_time_spent_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "question_attempts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("topic", models.CharField(blank=True, null=True)),
                ("difficulty", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("options", models.TextField()),
                ("correct_index", models.IntegerField()),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "questions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoadmapQuestion",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "roadmap_id",
                        "question_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "roadmap_question",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roadmaps",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "roadmaps",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("password_hash", models.TextField(blank=True, null=True)),
                (
                    "auth_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "provider_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfiles",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="question.users",
                    ),
                ),
                ("learning_streak", models.IntegerField(blank=True, null=True)),
                ("strong_topics", models.TextField(blank=True, null=True)),
                ("weak_topics", models.TextField(blank=True, null=True)),
                ("average_accuracy", models.FloatField(blank=True, null=True)),
                ("avg_difficulty", models.FloatField(blank=True, null=True)),
                ("average_time_per_question", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_profiles",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
