# Generated by Django 5.2.2 on 2025-06-08 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answers_questionattempts_questions_roadmapquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('options', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
            },
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='QuestionAttempts',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='RoadmapQuestion',
        ),
        migrations.DeleteModel(
            name='Roadmaps',
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
